name: Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        runtime_id:
        - win-x64
        - linux-x64
        - osx-x64
        - osx-arm64

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x
      - name: Build
        run: dotnet publish -r ${{ matrix.runtime_id }} -o dist/${{ matrix.runtime_id }}/git-jira --no-self-contained
      - uses: actions/upload-artifact@v4
        with:
          name: git-jira.${{ matrix.runtime_id }}
          path: dist/${{ matrix.runtime_id }}
